<?php
/**
 * @author Indusnet Team
 * @package Int_OutOfStock
 */
 
namespace Int\OutOfStock\Block\Form;
 
use Magento\Framework\View\Element\Template;
 
class Index extends Template
{
  public function __construct(Template\Context $context, array $data = [])
    {
        parent::__construct($context, $data);
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
  public function getProducts($productId)
  {
    /* ---------------ANY BUSINESS LOGIC---------*/
     return;
  }
}