<?php
/**
 * @author Indusnet Team
 * @package Int_OutOfStock
 */

namespace Int\OutOfStock\Block\Form;
 
use Magento\Framework\View\Element\Template;
 
class Post extends Template
{
  /**
     * @var \Int\OutOfStock\Helper\Data
     */
    private $moduleHelper;

    protected $_urlInterface;

    /**
     * @var \Magento\Framework\Url\Helper\Data
     */
    private $urlHelper;

    protected $customer;


  public function __construct(
    Template\Context $context,
    \Int\OutOfStock\Helper\Data $ModuleHelper,
    \Magento\Framework\Url\Helper\Data $urlHelper,
    \Magento\Framework\UrlInterface $urlInterface, 
    \Magento\Framework\App\Response\RedirectInterface $redirect,
    \Magento\Customer\Model\Session $customer,
    array $data = [])
    {
        parent::__construct($context, $data);
        $this->moduleHelper = $ModuleHelper;
        $this->urlHelper = $urlHelper;
        $this->_urlInterface = $urlInterface;
        $this->redirect = $redirect;
        $this->customer = $customer;
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
    /**
     * @return \Int\OutOfStock\Helper\Data
     */

    public function getOutOfStockHelper()
    {
        return $this->moduleHelper;
    }

    /**
     * @return string
     */
    public function getEncodedUrl()
    {
        return $this->urlHelper->getEncodedUrl();
    }

    /**
     * @return string
     */
    public function getCurrentUrl()
    {
        return $this->redirect->getRefererUrl();
    }

    /**
     * @return string
     */
    public function getCustomerEmail(){
    $customer = $this->customer;
    return $customer->getCustomer()->getEmail();
    
  }
}