<?php
/**
 * Accuride_Review
 *
 * @category    Alpine
 * @theme       Alpine_Accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Denis Furman <denis.furman@alpineinc.com>
 * @author      Andrey Nesterov <andrey.nesterov@alpineinc.com>
 *
 * @var $block \Magento\Review\Block\Product\ReviewRenderer
 */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<div class="wrapper_review">
    <?php if ($block->getReviewsCount()): ?>
        <?php $rating = $block->getRatingSummary(); ?>
        <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
            <?php if ($rating):?>
                <div class="rating-summary">
                    <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                    <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
             <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                 <span>
                     <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
                 </span>
             </span>
                    </div>
                </div>
                <span class="share_review"></span>
            <?php endif; ?>
            <div class="reviews-actions">
                <a class="action view"
                   href="<?= $block->escapeUrl($url) ?>">
                    <span itemprop="reviewCount"><?= $block->escapeHtml($block->getReviewsCount()) ?></span>&nbsp;
                    <span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span>
                </a>
                <a class="action add"
                   href="<?= $block->escapeUrl($urlForm) ?>"><?= $block->escapeHtml(__('Add Your Review')) ?></a>
            </div>
        </div>
    <?php elseif ($block->getDisplayIfEmpty()): ?>
        <div class="product-reviews-summary empty">
            <div class="reviews-actions">
                <a class="action add" href="<?= $block->escapeUrl($urlForm) ?>">
                    <?= $block->escapeHtml(__('Be the first to review this product')) ?>
                </a>
            </div>
        </div>
    <?php endif; ?>
    <!--<span class="icon_share"></span>-->
</div>
<?php // this is hardcoded per requirements in ACCU-659 ?>
<?php if(strpos($block->getProduct()->getSku(), '116RC') !== false) {
    $descClass = "description-open";
} else {
    $descClass = "description";
}
?>

<div class="<?= $descClass ?>">
    <?php echo html_entity_decode($block->getProduct()->getDescription()); ?>
</div>


