<?php
$helper = $block->getOutOfStockHelper();
$url = $helper->getSubscribtionUrl();
?>
<div class="amxnotif-container">
    <div class="category amxnotif-block subscribe-popup configurable-product-popup" data-action="<?php echo $url ?>">
        <form class="form-for-swatches-inputs-fix"></form>
        <form id="form-validate-stock-3744" class="subscribe-popup subscribe-popup-form" method="post" data-nofocus="true" action="<?php echo $url ?>" novalidate="novalidate">
                            <label for="notification-container">
                    Subscribe to back in stock notification</label>
                        <div class="notification-container" id="notification-container">
                <div class="input-fields fieldset">
                    <input name="guest_email" class="input-text amxnotif-guest-email" id="amxnotif-guest-email" size="30" type="email" data-validate="{required:true, 'validate-email':true }" placeholder="Insert your email" value="<?php echo $block->getCustomerEmail();?>">
                    <input type="hidden" name="product_id" value="">
                    <input type="hidden" name="parent_id" value="">
                    <input type="hidden" name="type" value="email">
                    <input type="hidden" name="getCurrentUrl" value="<?php echo $block->getCurrentUrl();?>"/>
                    
<input type="hidden"
                           name="<?= /* @noEscape */ \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>"
                           value="<?= /* @noEscape */ $block->getEncodedUrl() ?>"/>
                                    </div>

                <div class="actions-toolbar amxnotif_guest_action">
                    <div class="primary">
                        <button type="submit" class="action submit primary ">
                            Subscribe                        </button>
                    </div>
                </div>
                                    <span class="close-subscribe-popup">×</span>
                            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        "mage/mage",
        "mage/validation"
    ], function ($) {
        "use strict";

  $('.subscribe-popup-form').mage('validation');

 $(document).click(function(e){   //try to turn off popup
 var click=$(e.target);
 var outsideDiv=$(".subscribe-popup-form").parents();
 if(click.is(outsideDiv) || click.is(".close-subscribe-popup")){
 $('.configurable-product-popup').hide();
}
  }); 



    });
</script>