stage:
    deploy:
        MYSQL_USE_SLAVE_CONNECTION: true
        REDIS_USE_SLAVE_CONNECTION: true
        SCD_COMPRESSION_LEVEL: 4
        SCD_COMPRESSION_TIMEOUT: 600
        SEARCH_CONFIGURATION:
            engine: elasticsearch7
            elasticsearch7_server_hostname: 127.0.0.1
            elasticsearch7_server_port: '9200'
            elasticsearch7_index_prefix: magento2_stg
            elasticsearch7_server_timeout: '15'
    build:
        QUALITY_PATCHES:
        -   MDVA-35312
        -   MDVA-33975
        -   MDVA-34665
        -   MDVA-40134
        -   MDVA-39482
        -   MDVA-37082
        -   MDVA-37288-V2
        -   MDVA-30186
        -   MDVA-39935
    