<?php
/**
 * Accuride_Catalog
 *
 * @category    Alpine
 * @theme       Alpine_Accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Denis Furman <denis.furman@alpineinc.com>
 *
 */

?>
<!--It's temporary static content-->
<div class="specs_list">
    <ul>
        <li>1" [25.4 mm] over travel</li>
        <li>50" [12.7 mm] side space</li>
        <li>Non-disconnect</li>
        <li>Tested drawer width 16"</li>
        <li>Even lengths 12"—28" [305—711 mm]</li>
        <li>Clear zinc finish</li>
        <li>Up to 150 lb/68 kg</li>
    </ul>
    <ul>
        <li>Optional bracket kit available for electronic enclosure mounting</li>
        <li>4180-0219-XE Optional kit for enclosure or rack mount applications.</li>
    </ul>
</div>
