<?php
/**
 * Alpine_Cms
 *
 * @category    Alpine
 * @package     Alpine_Cms
 * @copyright   Copyright (c) 2018 Alpine Consulting, Inc
 * @author      Dmitry Naumov <dmitry.naumov@alpineinc.com>
 */
// @codingStandardsIgnoreFile
/** @var \Alpine\Cms\Block\QuoteForm $block */
?>
<div class="quote-index-index">
    <div class="wrapper_title_top">
        <p class="title_top"><?php echo __('QUOTE FORM') ?></p>
    </div>
</div>
