<?php
/**
 * Accuride_Catalog
 *
 * @category    Alpine
 * @theme       Alpine_Accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Denis Furman <denis.furman@alpineinc.com>
 * @author      Dmitry Naumov <dmitry.naumov@alpineinc.com>
 * @author      Kirilll Kosonogov <kirill.kosonogov@alpineinc.com>
 *
 * @var $block Magento\Catalog\Block\Product\View\Description
 */
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <?php
            $specificationsAttrValue = null;
            if ($product = $block->getProduct()){
                $specificationsAttr = $product->getCustomAttribute('specifications');
                if ($specificationsAttr){
                    $specificationsAttrValue = trim($specificationsAttr->getValue());
                }
            }
            // https://magento.stackexchange.com/questions/110796/change-order-of-tabs-on-product-page
            // We create a new array;
            $newPriority = array();
            // forEach the original $detailedInfoGroup Array;
            foreach ($detailedInfoGroup as $name){
                $alias = $layout->getElementAlias($name);
                // Get the priority which we applied via xml file
                // If no priority is applied via xml file then just set it to 10
                $priority = $block->getChildData($alias,'priority') ? $block->getChildData($alias,'priority') : '10';
                // variables pushed into new two-dimensional array
                array_push($newPriority, array($name, $priority));
            }
            // Sort array by priority
            usort($newPriority, function($a, $b) {
                return $a['1'] <=> $b['1'];
            });
        ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <div class="wrapper_titles desktop">
                <?php
                // Delete the original forEach statement
                //foreach ($detailedInfoGroup as $name)
                foreach ($newPriority as $name):?>
                    <?php
                    // rename $name[0] to $name because it's a two-dimensional array
                    // No further changes to this file, it works as explained
                    $name = $name[0];
                    if ($name == 'product.attributes' && !$specificationsAttrValue) {
                        continue;
                    }
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <div class="data item title"
                         aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                         data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @escapeNotVerified */ $alias ?>"
                           id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                            <?= /* @escapeNotVerified */ $label ?>
                        </a>
                    </div>
                <?php endforeach;?>
            </div>
            <div class="content_wrapper">
                <?php
                // Delete the original forEach statement
                //foreach ($detailedInfoGroup as $name)
                foreach ($newPriority as $name):?>
                <?php
                    // rename $name[0] to $name because it's a two-dimensional array
                    // No further changes to this file, it works as explained
                    $name = $name[0];
                    if ($name == 'product.attributes' && !$specificationsAttrValue) {
                        continue;
                    }
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <div class="data item title mobile"
                         aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                         data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-mobile">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @escapeNotVerified */ $alias ?>"
                           id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                            <?= /* @escapeNotVerified */ $label ?>
                        </a>
                    </div>
                    <div class="data item content " id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                        <div class="content_text">
                            <?= /* @escapeNotVerified */ $html ?>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function ($) {
        $('.item.mobile').on('click', function() {
            var attr = $(this).attr('aria-labeledby');
            setTimeout(function(){
                $('.desktop [id="' + attr + '"]').trigger('click');
            }, 10);
        });
    });
</script>
