
<?php $methodCode = "magedelight_cybersource"; 
$customHelper = $this->helper('Magedelight\Cybersource\Helper\Data');
$cybersourceIsEnabled = $customHelper->getConfig('payment/magedelight_cybersource/active');
if($cybersourceIsEnabled == 1) {
?>

<form action="<?php echo $block->getSaveUrl() ?>" name="cybersource_add_card"  data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'id="cybersource_add_card" method="post">
    <fieldset class="fieldset">
        <h2 class="legend"><?php echo __('Contact Information') ?></h2>
        <?php echo $block->getBlockHtml('formkey')?>



        <div class="field name-firstname required">
            <label for="<?php echo $methodCode ?>_firstname" class="label"><?php echo __('First Name') ?></label>
            <div class="control">
                <input type="text" id="<?php echo $methodCode ?>_firstname" name="<?php echo $methodCode ?>[address_info][firstname]" value="" title="<?php echo __('First Name') ?>" maxlength="255" class="input-text required-entry" />
            </div>
        </div>
        <div class="field name-lastname required">
            <label for="<?php echo $methodCode ?>_lastname" class="label"><?php echo __('Last Name') ?></label>
            <div class="control">
                <input type="text" id="<?php echo $methodCode ?>_lastname" name="<?php echo $methodCode ?>[address_info][lastname]" value="" title="<?php echo __('Last Name') ?>" maxlength="255" class="input-text required-entry">
            </div>
        </div>


        <div class="field">
            <label for="<?php echo $methodCode ?>_company" class="label"><?php echo __('Company') ?></label>
            <div class="control">
                <input type="text" name="<?php echo $methodCode ?>[address_info][company]" id="<?php echo $methodCode ?>_company" title="<?php echo __('Company') ?>" value="" class="input-text ">
            </div>
        </div>
        <div class="field required">
            <label for="<?php echo $methodCode ?>_street" class="label"><?php echo __('Street Address') ?></label>
            <div class="control">
                <input type="text" name="<?php echo $methodCode ?>[address_info][street]" value="" title="<?php echo __('Street Address') ?>" id="<?php echo $methodCode ?>_street" class="input-text  required-entry">
            </div>
        </div>

        <div class="field city required">
            <label for="<?php echo $methodCode ?>_city" class="label"><?php echo __('City') ?></label>
            <div class="control">
                <input type="text" name="<?php echo $methodCode ?>[address_info][city]" value="" title="<?php echo __('City') ?>" class="input-text  required-entry" id="<?php echo $methodCode ?>_city">
            </div>
        </div>
        <div class="field required state-required">
            <label for="<?php echo $methodCode ?>_region_id" class="label"><?php echo __('State/Province') ?></label>
            <div class="control">
                <select id="<?php echo $methodCode ?>_region_id" name="<?php echo $methodCode ?>[address_info][region_id]" title="<?php echo __('State/Province') ?>" class="validate-select" >
                    <option value=""><?php echo __('Please select region, state or province') ?></option>
                </select>

                <input type="text" id="<?php echo $methodCode ?>_state" name="<?php echo $methodCode ?>[address_info][state]" title="<?php echo __('State/Province') ?>" class="input-text required-entry" value="" />
            </div>
        </div>


        <div class="field zip required">
            <label for="<?php echo $methodCode ?>_zip" class="label"><?php echo __('Zip/Postal Code') ?></label>
            <div class="control">
                <input type="text" name="<?php echo $methodCode ?>[address_info][postcode]" value="" title="<?php echo __('Zip') ?>" id="<?php echo $methodCode ?>_zip" class="input-text validate-zip-international  required-entry">
            </div>
        </div>
        <div class="field">
            <label for="country" class="label"><?php echo __('Country') ?></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>


        <div class="field telephone required">
            <label for="<?php echo $methodCode ?>_telephone" class="label"><?php echo __('Telephone') ?></label>
            <div class="control">
                <input type="tel" name="<?php echo $methodCode ?>[address_info][telephone]" value="" title="<?php echo __('Telephone') ?>" class="input-text   required-entry" id="<?php echo $methodCode ?>_telephone">
            </div>
        </div>                


    </fieldset>


    <fieldset class="fieldset">
        <h2 class="legend"><?php echo __('Card Information') ?></h2>
       
        <div class="field cc_type required">
            <label for="<?php echo $methodCode ?>_cc_type" class="label"><?php echo __('Credit Card Type') ?></label>
            <div class="control">
                <select id="<?php echo $methodCode ?>_cc_type" data-validate="{required:true, 'validate-cyber-cc-type-select':'#<?php echo $methodCode ?>_cc_number'}" name="<?php echo $methodCode ?>[payment_info][cc_type]" class="required-entry validate-cyber-cc-type-select">
                    <option value=""><?php echo __('--Please Select--')?></option>
                    <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
                        <?php endforeach ?>
                </select>
            </div>
        </div>

        <div class="field _cc_number required">
            <label for="<?php echo $methodCode ?>_cc_number" class="label"><?php echo __('Credit Card Number') ?></label>
            <div class="control">
                <input type="text" id="<?php echo $methodCode ?>_cc_number" data-validate="{required:true, 'validate-number':true, 'validate-cyber-cc-type':'#<?php echo $methodCode ?>_cc_type'}" name="<?php echo $methodCode ?>[payment_info][cc_number]" title="<?php echo __('Credit Card Number') ?>"   class="input-text validate-cyber-cc-type" value="" autocomplete="off" />
            </div>
        </div>
        <div class="field expiration required">
            <label for="expiration" class="label"><?php echo __('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <?php $_ccExpMonth = '' ?>
                    <select id="<?php echo $methodCode ?>_expiration" name="<?php echo $methodCode ?>[payment_info][cc_exp_month]" data-validate="{'validate-cc-exp':'#<?php echo $methodCode ?>_expiration_yr'}" class="month validate-cc-exp required-entry"  style="width: 150px; margin-right: 10px;">                    
                        <?php foreach ($block->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = ''; ?>
                    <select id="<?php echo $methodCode ?>_expiration_yr" name="<?php echo $methodCode ?>[payment_info][cc_exp_year]" class="year required-entry " style="width: 150px;">
                        <?php foreach ($block->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>
        <?php if($block->hasVerification()): ?>
            <div class="field cc_cid required">
                <label for="<?php echo $methodCode ?>_cc_cid" class="label"><?php echo __('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo __('Card Verification Number') ?>" data-validate="{required:true, 'validate-cyber-cc-cvn':'#<?php echo $methodCode ?>_cc_type'}" class="input-text" id="<?php echo $methodCode ?>_cc_cid" name="<?php echo $methodCode ?>[payment_info][cc_cid]" value=""  autocomplete="off" />
                    </div>
                </div>
            </div>
            <?php endif; ?>

        <div class="buttons-set">
            <input type="hidden" name="<?php echo $methodCode ?>[card_mode]" value="add" />
            <p class="back-link"><a href="<?php echo $block->getBackUrl() ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
            <button type="button"  onclick="saveCardForm()" title="<?php echo __('Save Card') ?>" class="button button action tocart primary" id="cybersource_add_card_btn"><span><span><?php echo __('Save Card') ?></span></span></button>
        </div>  
    </fieldset>
</form>
<?php } ?>
<script>
 function saveCardForm()
 {
     var dataForm = jQuery('#cybersource_add_card');
    dataForm.mage('validation');
    if (jQuery('#cybersource_add_card').valid()) {
              jQuery('#cybersource_add_card_btn').attr('disabled',true);
              jQuery('#cybersource_add_card').submit();
     }
 }
require([
    'jquery',
    'mage/mage'
], function($){

//    var dataForm = $('#cybersource_add_card');
//    dataForm.mage('validation');
//    if ($('#cybersource_add_card').valid()) {
//                   console.log("success");
//                  }

});
</script>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#<?php echo $methodCode ?>_region_id",
                "regionInputId": "#<?php echo $methodCode ?>_state",
                "postcodeId": "#<?php echo $methodCode ?>_zip",
                "form": "#cybersource_add_card",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo "0" ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>