<?php
/**
 * @author Atwix Team
 * @copyright Copyright (c) 2016 Atwix (https://www.atwix.com/)
 * @package Atwix_Richsnippets
 *
 * @var $block \Atwix\Richsnippets\Block\Catalog\CategoryVisible
 *
 * @see \Atwix\Richsnippets\Block\Catalog\CategoryVisible::makeCategorySnippets() for assing $categorySnippets
 * @var $categorySnippets array
 */
?>
<div class="snippets-footer">
	<div itemscope itemtype="http://schema.org/Product">
		<ul class="snippets-fields">
            <?php if (isset($categorySnippets['description']) && $categorySnippets['description']) : ?>
                <li>
                    <span itemprop="description"><?php echo $categorySnippets['description']; ?></span>
                </li>
            <?php endif; ?>
            <?php if((isset($categorySnippets['rating']['count'])) && ($categorySnippets['rating']['percentage'] > 0)) { ?>
				<li><?php echo __('Our %1 has been rated %2 based on %3 individual customer review(s)',
									'<span itemprop="name">' . $categorySnippets['name'] . '</span>',
									'<span itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
										<span itemprop="ratingValue">' . $categorySnippets['rating']['avg']  . '</span>/<span itemprop="bestRating">' . $categorySnippets['rating']['best'] . '</span>',
									'<span itemprop="' . $categorySnippets['rating']['type'] . '">' . $categorySnippets['rating']['count'] . '</span></span>'
					); ?>
				</li>
			<?php } else { ?>
				<li><span itemprop="name"><?php echo $categorySnippets['name']; ?></span></li>
			<?php } ?>
			<li>
					<span itemprop="offers" itemscope itemtype="http://schema.org/AggregateOffer">
						<?php if(isset($categorySnippets['offers']['price_low'])) { ?>
							<?php if(isset($categorySnippets['offers']['price_high'])) { ?>
								<?php echo __('Prices from %1 to %2',
												'<span itemprop="lowPrice" content="' . $categorySnippets['offers']['clean_low'] . '">' . $categorySnippets['offers']['price_low']  . '</span>',
												'<span itemprop="highPrice" content="' . $categorySnippets['offers']['clean_high'] . '">' . $categorySnippets['offers']['price_high'] . '</span>'
								); ?>
							<?php } else { ?>
								<?php echo __('Starting at:'); ?>
								<span itemprop="lowprice" content="<?php echo $categorySnippets['offers']['clean_low']; ?>">
									<?php echo $categorySnippets['offers']['price_low']; ?>
								</span>
							<?php } ?>
						<?php } else { ?>
							<?php echo __('Price:'); ?>
							<span itemprop="price" content="<?php echo $categorySnippets['offers']['clean']; ?>">
								<?php echo $categorySnippets['offers']['price']; ?>
							</span>
						<?php } ?>
						<meta itemprop="priceCurrency" content="<?php echo $categorySnippets['offers']['currency']; ?>" />
						<?php if(isset($categorySnippets['availability'])) { ?>
							<link itemprop="availability" href="<?php echo $categorySnippets['availability']; ?>">
						<?php } ?>
					</span>
			</li>
			<?php if(isset($categorySnippets['extra'])) { ?>
				<?php foreach($categorySnippets['extra'] as $field) { ?>
					<li><?php echo __($field['label']) . ': ' . $field['value']; ?></li>
				<?php } ?>
			<?php } ?>
		</ul>
	</div>
</div>	