<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */

?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
        <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                <?php else : ?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif ?>
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
                <?php if ($_total->getStrong()) : ?>
                    <strong>
                        <?= /* @noEscape */ $block->formatValue($_total) ?>
                        <?php
                        if (($_code == 'grand_total' || $_code == 'subtotal')  && $block->getOrder()->isCurrencyDifferent()) {
                            $val = $block->getOrder()->formatBasePrice($block->getSource()->getData('base_'.$_code));
                            echo "(".$val.")";
                        }
                        if ($_code == 'shipping' && $block->getOrder()->isCurrencyDifferent()) {
                            $val = $block->getOrder()->formatBasePrice($block->getSource()->getBaseShippingAmount());
                            echo "(".$val.")";
                        }
                        ?>
                    </strong>
                <?php else : ?>
                    <?= /* @noEscape */ $block->formatValue($_total) ?>
                    <?php  if (($_code == 'grand_total' || $_code == 'subtotal')  && $block->getOrder()->isCurrencyDifferent()) {
                        $val = $block->getOrder()->formatBasePrice($block->getSource()->getData('base_'.$_code));
                        echo "(".$val.")";
                    }
                    if ($_code == 'shipping' && $block->getOrder()->isCurrencyDifferent()) {
                        $val = $block->getOrder()->formatBasePrice($block->getSource()->getBaseShippingAmount());
                        echo "(".$val.")";
                    }
                    ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach?>