<?php
/**
 * Accuride_Catalog
 *
 * @category    Alpine
 * @theme       Alpine_Accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Denis Furman <denis.furman@alpineinc.com>
 * @author      Aleksandr Mikhailov <aleksandr.mikhailov@alpineinc.com>
 * @author      Andrey Nesterov <andrey.nesterov@alpineinc.com>
 * @author      Evgeniy Derevyanko <evgeniy.derevyanko@alpineinc.com>
 * 
 * @var $block \Alpine\Catalog\Block\Product\ListProduct
 */
use Magento\Framework\App\Action\Action;
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$onlineProducts = $block->getOnlineProducts();
$otherProducts = $block->getOtherProducts();

$onlineOrOtherProductsExists = count($onlineProducts) || count($otherProducts);
?>
<?php if (!$_productCollection->count() || !$onlineOrOtherProductsExists): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php if (count($onlineProducts)) : ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <div class="title_top">
            <?php echo __('Available online') ?>
        </div>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($onlineProducts as $_product): ?>
                <li class="item product product-item <?php echo $_product->getTypeId() == 'configurable' ? 'conf' : ''?>" id="<?php echo $_product->getId(); ?>">
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo <?php echo $_product->getCrossSectionImage() ? 'cross_change' : ''?>" tabindex="-1">
                        <span class="photo pr_image active">
                           <?php echo $productImage->toHtml(); ?>
                        </span>
                        <?php if ($_product->getCrossSectionImage()): ?>
                            <span class="cross pr_image">
                                <?php 
                                if (trim($_product->getCrossSectionImage()) != 'no_selection') {
                                    echo $block->getImage($_product, 'catalog_cross_section_image')->toHtml(); 
                                } else {
                                    echo $productImage->toHtml();
                                }
                                ?>
                            </span>
                        <?php endif; ?>

                        <?php if ($_product->hasData('is_top_choice') && $_product->getData('is_top_choice')) : ?>
                            <div class="label_product">
                                <img src="<?php echo $block->getViewFileUrl('images/icons/vector-smart-object.png'); ?>" alt="label">
                            </div>
                        <?php endif; ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php if ($_product->getTypeId() == 'configurable'): ?>
                            <div class="conf_options">
                                <?php
                                $attrValueConfigs = $_product->getTypeInstance()->getConfigurableAttributesAsArray($_product);
                                if (sizeof($attrValueConfigs)):
                                    ?>
                                    <?php foreach ($attrValueConfigs as $attrValueConfig): ?>
                                    <?php
                                    $attributeCode = $attrValueConfig['attribute_code'];
                                    $attributeId = $attrValueConfig['attribute_id'];
                                    ?>
                                    <select name="super_attribute[<?php echo $attributeId; ?>]"
                                            id="attribute_<?php echo $attributeId; ?>_<?php echo $_product->getId(); ?>"
                                            >
                                        <option value="">
                                            <?php echo $block->escapeHtml($attrValueConfig['frontend_label']); ?>
                                        </option>
                                        <?php foreach ($attrValueConfig['values'] as $attrOptionValue): ?>
                                            <option value="<?php echo $attrOptionValue['value_index']; ?>">
                                                <?php echo $block->escapeHtml($attrOptionValue['label']); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                <?php endforeach; ?>
                                <?php endif; ?>
                                <div class="field qty">
                                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                                            __('Quantity:') ?></span></label>
                                    <div class="control">
                                        <span class="minus update"></span>
                                        <input type="number"
                                               id="qty"
                                               value="<?php echo $block->getProductDefaultQty($_product) * 1 ?>"
                                               title="<?php echo __('Quantity:') ?>"
                                               class="input-text qty"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>"
                                        />
                                        <span class="plus update"></span>
                                        <span class="uom"><?php echo $block->escapeHtml($_product->getAttributeText('uom')); ?></span>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product sku product-item-link"><?php
                            echo $_helper->productAttribute($_product, $_product->getSku(), 'sku');
                        ?></strong>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>

                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <?php if ($_product->getTypeId() == 'configurable'): ?>
                                                <input type="hidden" name="selected_configurable_option">
                                                <input type="hidden" name="qty">
                                                <?php
                                                $attrValueConfigs = $_product->getTypeInstance()->getConfigurableAttributesAsArray($_product);
                                                if (sizeof($attrValueConfigs)):
                                                ?>
                                                    <?php foreach ($attrValueConfigs as $attrValueConfig): ?>
                                                        <input type="hidden"
                                                            name="super_attribute[<?php echo $attrValueConfig['attribute_id']; ?>]"
                                                            class="attribute_<?php echo $attrValueConfig['attribute_id']; ?>_<?php echo $_product->getId(); ?>">
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <a href="<?php echo $_product->getProductUrl()?>" class="action blue primary"><span><?php echo __('DETAILS') ?></span></a>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                            
                            <?php
                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                    ?>
                    <a href="#"
                       class="action tocompare custom-tocompare"
                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                       role="button">
                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                    </a>
                        </div>
                    </div>
                </div>
                    
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php endif; ?>
    <?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <?php if (count($otherProducts)) : ?>
        <div class="other_products products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
            <div class="title">
                <?php echo __('Other products') ?>
            </div>
            <?php $iterator = 1; ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($otherProducts as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-grid">
                            <?php $productImage = $block->getImage($_product, 'category_page_grid'); ?>
                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo <?php echo $_product->getCrossSectionImage() ? 'cross_change' : ''?>" tabindex="-1">
                                <span class="photo pr_image active">
                                   <?php echo $productImage->toHtml(); ?>
                                </span>
                                <?php if ($_product->getCrossSectionImage()): ?>
                                    <span class="cross pr_image">
                                        <?php 
                                        if (trim($_product->getCrossSectionImage()) != 'no_selection') {
                                            echo $block->getImage($_product, 'catalog_cross_section_image')->toHtml(); 
                                        } else {
                                            echo $productImage->toHtml();
                                        }
                                        ?>
                                    </span>
                                <?php endif; ?>

                                <?php if ($_product->hasData('is_top_choice') && $_product->getData('is_top_choice')) : ?>
                                    <div class="label_product">
                                        <img src="<?php echo $block->getViewFileUrl('images/icons/vector-smart-object.png'); ?>" alt="label">
                                    </div>
                                <?php endif; ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product sku product-item-link"><?php
                                    echo $_helper->productAttribute($_product, $_product->getSku(), 'sku');
                                ?></strong>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <a href="<?php echo $_product->getProductUrl()?>" class="action blue primary"><span><?php echo __('View product') ?></span></a>
                                        </div>
                                    </div>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare custom-tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php echo __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <?= $block->getOtherProductsToolbarHtml() ?>
    <?php endif; ?>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $block->stripTags($_product->getSku(), null, true) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        ".product-items .product-item": {
            "Magento_Catalog/js/qty": {},
            "Magento_Catalog/js/hover":{
            }
        },
        "*": {
            "Magento_Catalog/js/prepare-configurable-to-cart": {
                "spConfig": <?php echo $block->getSpConfig(); ?>,
                "priceConfigs": <?php echo $block->getPriceConfigs(); ?>
            }
        }
    }
</script>
    <div class="intnotif-container"></div>
<script type="text/javascript">
    require([
        'jquery',
        "mage/mage",
        "mage/validation"
    ], function ($) {
        "use strict";

    $('.subscribe-popup-form').mage('validation');

    $(document).click(function(e){
        var click=$(e.target);
        var outsideDiv=$(".subscribe-popup-form").parents();
        if(click.is(outsideDiv) || click.is(".close-subscribe-popup")){
            $('.configurable-product-popup').hide();
        }
    }); 
    });
</script>