<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($category_sidebar_content = $block->getCurrentCategory()->getCategorySidebarContent()) :?>
    <div class="category-description">
        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $category_sidebar_content,
            'category_sidebar_content'
        ) ?>
    </div> 
<?php endif; ?>
