<?php
/**
 * Alpine_Acton
 *
 * @category    Alpine
 * @package     Alpine_Acton
 * @copyright   Copyright (c) 2018 Alpine Consulting, Inc (www.alpineinc.com)
 * @author      Aleksandr Mikhailov (aleksandr.mikhailov@alpineinc.com)
 */

/** @var \Alpine\Acton\Block\CheckoutSuccessIframe $block */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "placeActonIframe": <?php echo $block->getPlaceActonIframeConfig(); ?>
        }
    }
</script>