<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Accuride_Catalog
 *
 * @category    Alpine
 * @theme       Alpine_Accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Evgeniy Derevyanko <evgeniy.derevyanko@alpineinc.com>
 */

use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php
$blockObj = $block->getLayout()->createBlock(\Alpine\Catalog\Block\Product\ListProduct::class);
$otherProducts = $blockObj->getOtherProducts();
$totalNum = $block->getTotalNum() + $otherProducts->getSize();
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?php /* @escapeNotVerified */ echo __('Items %1-%2 of %3',
            '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
            '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
            '<span class="toolbar-number">' . $totalNum . '</span>') ?>
    <?php elseif ($totalNum == 1): ?>
        <?php /* @escapeNotVerified */ echo __('%1 Item',
           '<span class="toolbar-number">' . $totalNum . '</span>') ?>
    <?php else: ?>
        <?php /* @escapeNotVerified */ echo __('%1 Items',
            '<span class="toolbar-number">' . $totalNum . '</span>') ?>
    <?php endif; ?>
</p>
