<?php
/**
 * Alpine_VideoWidget
 *
 * @category    Alpine
 * @theme       Alpine_accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Lev Zamansky <lev.zamanskiy@alpineinc.com>
*/
?>
<script>
    require([
        'jquery',
        'footer-video'
    ], function ($) {
        $(function () { // to ensure that code evaluates on page load
            $('body').footerVideo({});
        });
    });
</script>
