<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Acart
 */
?>
<?php
// phpcs:ignore
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
?>

<ul style="list-style-type: none; padding-top: 10px;">
    <?php if ($block->getQuote()): ?>
        <?php foreach ($block->getItems() as $_item): ?>
            <?php $_product = $block->getProduct($_item); ?>
            <li style="border-bottom: 1px solid #F0F0F0; padding: 5px 0px;">

                <?php if ($block->showImage()): ?>
                    <?php $block->initProductImageHelper($_product, 'amasty_acart_items_list'); ?>
                    <?php $_imageHelper = $block->getProductImageHelper(); ?>
                    <div style="display: table-cell; vertical-align: top;">
                        <a style="text-decoration:none !important;"
                           href="<?= $block->escapeUrl($block->getProductUrl($_product)); ?>">
                            <img src="<?= $block->escapeUrl($block->prepareProductImageUrl($_imageHelper->getUrl())) ?>"
                                 alt="<?= $block->escapeHtml($_imageHelper->getLabel()) ?>"
                                 width="<?= $block->escapeHtml($_imageHelper->getWidth()) ?>"
                                 height="<?= $block->escapeHtml($_imageHelper->getHeight()) ?>"/>
                        </a>
                    </div>
                <?php endif; ?>

                <div style="display: table-cell; vertical-align: top;">
                    <div style="font-size: 1.8rem; margin: -3px 0 5px;">
                        <a style="text-decoration:none !important;"
                           href="<?= $block->escapeUrl($block->getProductUrl($_product)); ?>">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </div>
                    <?php if ($block->showOptionList() && $_options = $block->getProductOptions($_item, $_product)): ?>
                        <dl>
                            <?php foreach ($_options as $_option): ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt style="float: left; clear: left; padding-right: 5px;"><?= $block->escapeHtml($_option['label']) ?>:
                                </dt>
                                <dd style="float: left;">
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                                    <?php else: ?>
                                        <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                    <div style="clear: left;">
                        <?php if ($block->showDescription()): ?>
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?>
                        <?php endif; ?>
                    </div>
                    <div>
                        <?php if ($block->showPrice()): ?>
                            <span style="padding-right: 5px; font-weight: 700; margin-bottom: 5px; margin-top: 0;"><?= $block->escapeHtml(__('Price')) ?>: </span>
                            <span style="font-size: 1.8rem; color: #666666;">
                            <?= /* @noEscape */ $block->getPrice($_product); ?>
                        </span>
                        <?php endif; ?>
                    </div>
                </div>

            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
