<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Stockstatus
 */
?>
<div class="messages" style="position: relative; top: -25px;">
    <div class="message message-notice">
        <?= __('You can use the following variables: {qty-threshold}, {qty}, {tomorrow}, {day-after-tomorrow}, {yesterday}, {expected_date} or any product attributes.') ?>
    </div>
</div>
