<?php
/**
* Magedelight
* Copyright (C) 2017 Magedelight <info@magedelight.com>
*
* NOTICE OF LICENSE
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
*
* @category Magedelight
* @package Magedelight_Cybersourcedc
* @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
use Magento\Vault\Api\Data\PaymentTokenInterface;
$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
$blockObj= $block->getLayout()->createBlock('Magedelight\Cybersourcesop\Block\Customer\Addcard');
$method_code = "cybersourcesop";
?>
<tr>
    <td data-th="<?php echo $block->escapeHtml(__('Card Number')) ?>" class="col card-number">
        <span><?php echo $block->escapeHtml(__('ending')); ?></span> <?php /* @noEscape */  echo $ccNumberView ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?php echo $block->escapeHtml($block->getExpDate()); ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Type')) ?>" class="col card-type">
        <img src="<?php /* @noEscape */ echo $block->getIconUrl(); ?>"
             width="<?php /* @noEscape */ echo $block->getIconWidth(); ?>"
             height="<?php /* @noEscape */ echo $block->getIconHeight(); ?>"
        >
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
        <?php if ($block->getMethodCode() != "" && $block->getMethodCode() == $method_code) { ?>
            <form class="form" method="post" name="form_edit_<?php echo $block->getToken()->getEntityId(); ?>" action="<?php echo $blockObj->getPostUrl(); ?>">
                <?php echo $block->getBlockHtml('formkey')?>
                <input type="hidden" name="card_id" value="<?php echo $block->getToken()->getEntityId(); ?>" />
                <input
                name="<?php /* @noEscape */ echo PaymentTokenInterface::PUBLIC_HASH?>"
                value="<?php /* @noEscape */ echo $block->getToken()->getPublicHash()?>"
                type="hidden"/>
                <button class="action primary edit" name="profile_edit" value="edit" type="submit"><span><span><?php echo __("Edit") ?></span></span></button>
            </form> 
        <?php } ?>
        <form
            class="form"
            action="<?php echo $block->escapeUrl($block->getUrl('vault/cards/deleteaction')); ?>"
            method="post"
            >
            <?php echo $block->getBlockHtml('formkey')?>
            <input
                name="<?php /* @noEscape */ echo PaymentTokenInterface::PUBLIC_HASH?>"
                value="<?php /* @noEscape */ echo $block->getToken()->getPublicHash()?>"
                type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "<?php echo $block->escapeHtml(__('Delete')) ?>",
                                        "content": "Are you sure you want to delete this card: <?php
                                            /* @noEscape */ echo $ccNumberView
                                        ?>?"
                                    }
                                }'>
                <span><?php echo $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
