<?php
/**
 * Accuride_Catalog
 *
 * @category    Alpine
 * @theme       Alpine_Accuride
 * @copyright   Copyright (c) 2018 Alpine Consulting Inc.
 * @author      Denis Furman <denis.furman@alpineinc.com>
 * @author      Evgeniy Derevyanko <evgeniy.derevyanko@alpineinc.com>
 *
 * @var block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar toolbar-products" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
    <?php if ($block->isExpanded()): ?>
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
    <?php endif; ?>

    <div class="cross switcher" data-mage-init='{"Magento_Catalog/js/switcher":{}}'>
        <span class="type cross"><?php echo __('CROSS SECTION') ?></span>
        <label class="switch">
            <input type="checkbox">
            <span class="slider"></span>
        </label>
        <span class="type photo active"><?php echo __('PHOTO') ?></span>
    </div>

    <?= $block->getPagerHtml() ?>

    <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

    <?php if ($block->isExpanded()): ?>
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
    <?php endif; ?>
</div>
